version: '3.8'
services:
  web:
    build: .
    command: make gunicorn
    expose:
      - 8000
    env_file: .env
    depends_on: db
    volumes:
      - static_volume:/usr/src/app/static
  db:
    image: postgres:13-alpine
    env_file: .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8081:80
    depends_on:
      - web

volumes:
  static_volume:
